[package]
name = "raffaello-core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
color-eyre = "0.6.5"
futures = "0.3.31"
ratatui = { version = "0.29.0", features = ["macros"] }
tokio = { version = "1.47.1", features = ["sync"] }
